import type { AppKey } from "@/lib/types/access-log";

export const APP_LABELS: Record<AppKey, string> = {
  stocks: "保有株",
  disney: "ディズニー",
  costs: "コスト分析",
  council: "AI 合議",
  docs: "資料生成",
  works: "WORKS",
  space: "宇宙分析",
  users: "ユーザー",
  system: "システム",
};

export const FEATURE_LABELS: Record<string, string> = {
  "stock-analysis": "保有株 AI アドバイス",
  "disney-suggest": "ディズニー AI ガイド",
  "disney-chat": "ディズニー ミッキーチャット",
  "council-initial-logic": "合議 初見（論理）",
  "council-initial-creative": "合議 初見（発想）",
  "council-initial-skeptic": "合議 初見（懐疑）",
  "council-rebuttal-logic": "合議 議論（論理）",
  "council-rebuttal-creative": "合議 議論（発想）",
  "council-rebuttal-skeptic": "合議 議論（懐疑）",
  "council-synthesis-judge": "合議 まとめ（議長）",
  "council-followup": "合議 フォローアップ",
  "docs-generate": "資料生成 pptx",
  "works-consult": "WORKS AI 相談（Gemini 無料枠）",
  "works-summary": "WORKS まとめ生成（Gemini 無料枠）",
  "works-money-flow": "WORKS 行政・お金の流れ",
  "judicial-case-chat": "WORKS 訴訟記録ノート",
  "space-chat": "宇宙 AI 解説",
  "space-apod-ja": "宇宙 APOD 日本語解説",
  watches: "保有株一覧",
  "watch-detail": "保有株詳細",
  lookup: "銘柄検索",
  advice: "ディズニーアドバイス",
  waits: "待ち時間",
  status: "混雑ステータス",
  calendar: "混雑カレンダー",
  chat: "チャット",
  dashboard: "分析ダッシュボード",
  profile: "ユーザープロファイル",
  ask: "合議 質問",
  "ask-step": "合議 ステップ実行",
  config: "合議 設定",
  followup: "合議 フォローアップ",
  generate: "資料生成",
  consult: "WORKS AI 相談",
  summarize: "WORKS まとめ",
  notes: "WORKS メモ",
  "money-flow": "行政・お金の流れ",
  "case-chat": "訴訟記録チャット",
  apod: "APOD タイムライン",
  "apod-summary": "APOD 日本語解説",
  neo: "小惑星 NEO",
  "neo-image": "小惑星画像",
  tracks: "鷹の目 軌道",
  "azure-infra": "Azure インフラコスト",
  "access-analytics": "アクセス情報分析",
  "public-access-analytics": "公開アクセス分析",
  pageview: "公開ページビュー",
};

export const FEATURE_APP_MAP: Record<string, AppKey> = {
  "stock-analysis": "stocks",
  "disney-suggest": "disney",
  "disney-chat": "disney",
  "council-initial-logic": "council",
  "council-initial-creative": "council",
  "council-initial-skeptic": "council",
  "council-rebuttal-logic": "council",
  "council-rebuttal-creative": "council",
  "council-rebuttal-skeptic": "council",
  "council-synthesis-judge": "council",
  "council-followup": "council",
  "docs-generate": "docs",
  "works-consult": "works",
  "works-summary": "works",
  "works-money-flow": "works",
  "judicial-case-chat": "works",
  "space-chat": "space",
  "space-apod-ja": "space",
  watches: "stocks",
  "watch-detail": "stocks",
  lookup: "stocks",
  advice: "disney",
  waits: "disney",
  status: "disney",
  calendar: "disney",
  dashboard: "costs",
  profile: "users",
  ask: "council",
  "ask-step": "council",
  config: "council",
  followup: "council",
  generate: "docs",
  consult: "works",
  summarize: "works",
  notes: "works",
  "money-flow": "works",
  "case-chat": "works",
  apod: "space",
  "apod-summary": "space",
  neo: "space",
  "neo-image": "space",
  tracks: "space",
  chat: "system",
  "azure-infra": "costs",
  "access-analytics": "costs",
};

export function featureLabel(feature: string): string {
  return FEATURE_LABELS[feature] ?? feature;
}

export function featureApp(feature: string): AppKey {
  return FEATURE_APP_MAP[feature] ?? "system";
}
