/** 鷹の目 — 地上カメラ・公開ライブ映像カタログ */

export type GroundMediaType = "video" | "image";

export interface GroundCamera {
  id: string;
  name: string;
  type:
    | "防犯カメラ"
    | "車載カメラ"
    | "ドローンカメラ"
    | "固定カメラ"
    | "ライブカメラ"
    | "河川カメラ"
    | "道路カメラ"
    | "個人カメラ"
    | "静止画";
  country: string;
  region?: string;
  lat: number;
  lon: number;
  headingDeg: number;
  fovDeg: number;
  rangeM: number;
  mediaType: GroundMediaType;
  mediaUrl: string;
  sourceLabel?: string;
  sourceUrl?: string;
}

function yt(id: string): string {
  return `https://www.youtube.com/embed/${id}?autoplay=1&mute=1&rel=0`;
}

/**
 * 公開地上カメラ／映像のキュレーション。
 * @see https://livecam.asia/
 * @see https://camera-map.com/
 * @see https://webcamera24.com/ja/
 */
export const GROUND_CAMERAS: GroundCamera[] = [
  {
    id: "shibuya-sky",
    name: "渋谷スクランブル（SHIBUYA SKY）",
    type: "ライブカメラ",
    country: "日本",
    region: "東京",
    lat: 35.6595,
    lon: 139.7004,
    headingDeg: 45,
    fovDeg: 70,
    rangeM: 120,
    mediaType: "video",
    mediaUrl: yt("3Q5wZeTuttw"),
    sourceLabel: "YouTube / SHIBUYA SKY",
    sourceUrl: "https://www.youtube.com/watch?v=3Q5wZeTuttw",
  },
  {
    id: "shibuya",
    name: "渋谷スクランブル交差点",
    type: "ライブカメラ",
    country: "日本",
    region: "東京",
    lat: 35.658,
    lon: 139.7015,
    headingDeg: 30,
    fovDeg: 70,
    rangeM: 110,
    mediaType: "video",
    mediaUrl: yt("DjdUEyjx8GM"),
    sourceLabel: "YouTube ライブ",
    sourceUrl:
      "https://www.youtube.com/results?search_query=%E6%B8%8B%E8%B0%B7+%E3%83%A9%E3%82%A4%E3%83%96%E3%82%AB%E3%83%A1%E3%83%A9",
  },
  {
    id: "shibuya-4k",
    name: "渋谷交差点 4K",
    type: "ライブカメラ",
    country: "日本",
    region: "東京",
    lat: 35.6602,
    lon: 139.699,
    headingDeg: 90,
    fovDeg: 75,
    rangeM: 100,
    mediaType: "video",
    mediaUrl: yt("IFzpwTnv23w"),
    sourceLabel: "YouTube ライブ",
    sourceUrl: "https://www.youtube.com/watch?v=IFzpwTnv23w",
  },
  {
    id: "shinjuku-live",
    name: "新宿歌舞伎町",
    type: "ライブカメラ",
    country: "日本",
    region: "東京",
    lat: 35.6938,
    lon: 139.7034,
    headingDeg: 135,
    fovDeg: 75,
    rangeM: 100,
    mediaType: "video",
    mediaUrl: yt("DjdUEyjx8GM"),
    sourceLabel: "ライブカメラDB 参考",
    sourceUrl: "https://livecam.asia/",
  },
  {
    id: "tokyo-tower",
    name: "東京タワー周辺",
    type: "固定カメラ",
    country: "日本",
    region: "東京",
    lat: 35.6586,
    lon: 139.7454,
    headingDeg: 180,
    fovDeg: 55,
    rangeM: 200,
    mediaType: "video",
    mediaUrl: yt("1-iS7LArP0Y"),
    sourceLabel: "YouTube ライブ",
    sourceUrl: "https://camera-map.com/",
  },
  {
    id: "akihabara",
    name: "秋葉原エリア",
    type: "車載カメラ",
    country: "日本",
    region: "東京",
    lat: 35.6984,
    lon: 139.7731,
    headingDeg: 270,
    fovDeg: 90,
    rangeM: 80,
    mediaType: "video",
    mediaUrl: yt("1-iS7LArP0Y"),
    sourceLabel: "YouTube ライブ",
    sourceUrl: "https://livecam.asia/",
  },
  {
    id: "skytree-live",
    name: "東京スカイツリー展望ライブ",
    type: "ライブカメラ",
    country: "日本",
    region: "東京",
    lat: 35.7101,
    lon: 139.8107,
    headingDeg: 225,
    fovDeg: 50,
    rangeM: 300,
    mediaType: "video",
    mediaUrl: yt("DjdUEyjx8GM"),
    sourceLabel: "YouTube ライブ",
    sourceUrl:
      "https://www.youtube.com/results?search_query=%E3%82%B9%E3%82%AB%E3%82%A4%E3%83%84%E3%83%AA%E3%83%BC+%E3%83%A9%E3%82%A4%E3%83%96%E3%82%AB%E3%83%A1%E3%83%A9",
  },
  {
    id: "rainbow-bridge",
    name: "レインボーブリッジ・お台場",
    type: "ライブカメラ",
    country: "日本",
    region: "東京",
    lat: 35.6366,
    lon: 139.7755,
    headingDeg: 45,
    fovDeg: 65,
    rangeM: 220,
    mediaType: "video",
    mediaUrl: yt("1-iS7LArP0Y"),
    sourceLabel: "ライブカメラ検索マップ",
    sourceUrl: "https://camera-map.com/",
  },
  {
    id: "asakusa",
    name: "浅草・雷門周辺",
    type: "ライブカメラ",
    country: "日本",
    region: "東京",
    lat: 35.7148,
    lon: 139.7967,
    headingDeg: 180,
    fovDeg: 60,
    rangeM: 120,
    mediaType: "video",
    mediaUrl: yt("IFzpwTnv23w"),
    sourceLabel: "YouTube ライブ",
    sourceUrl: "https://livecam.asia/",
  },
  {
    id: "disney-area",
    name: "舞浜・TDR 周辺",
    type: "ライブカメラ",
    country: "日本",
    region: "千葉",
    lat: 35.6329,
    lon: 139.8804,
    headingDeg: 0,
    fovDeg: 60,
    rangeM: 180,
    mediaType: "video",
    mediaUrl: yt("DjdUEyjx8GM"),
    sourceLabel: "ライブカメラDB（観光）",
    sourceUrl: "https://livecam.asia/",
  },
  {
    id: "haneda",
    name: "羽田空港アプローチ",
    type: "道路カメラ",
    country: "日本",
    region: "東京",
    lat: 35.5494,
    lon: 139.7798,
    headingDeg: 315,
    fovDeg: 60,
    rangeM: 150,
    mediaType: "video",
    mediaUrl: yt("1-iS7LArP0Y"),
    sourceLabel: "YouTube / 道路ライブ",
    sourceUrl:
      "https://www.youtube.com/results?search_query=%E7%BE%BD%E7%94%B0+%E3%83%A9%E3%82%A4%E3%83%96%E3%82%AB%E3%83%A1%E3%83%A9",
  },
  {
    id: "narita-road",
    name: "成田空港周辺道路",
    type: "道路カメラ",
    country: "日本",
    region: "千葉",
    lat: 35.772,
    lon: 140.3929,
    headingDeg: 270,
    fovDeg: 55,
    rangeM: 180,
    mediaType: "video",
    mediaUrl: yt("1-iS7LArP0Y"),
    sourceLabel: "ライブカメラ検索マップ",
    sourceUrl: "https://camera-map.com/",
  },
  {
    id: "shutoko-ginza",
    name: "首都高・銀座付近",
    type: "道路カメラ",
    country: "日本",
    region: "東京",
    lat: 35.672,
    lon: 139.765,
    headingDeg: 20,
    fovDeg: 55,
    rangeM: 140,
    mediaType: "video",
    mediaUrl: yt("1-iS7LArP0Y"),
    sourceLabel: "YouTube 国道・高速ライブ",
    sourceUrl:
      "https://www.youtube.com/results?search_query=%E9%A6%96%E9%83%BD%E9%AB%98+%E3%83%A9%E3%82%A4%E3%83%96",
  },
  {
    id: "yokohama-bay",
    name: "横浜ベイブリッジ",
    type: "道路カメラ",
    country: "日本",
    region: "神奈川",
    lat: 35.455,
    lon: 139.675,
    headingDeg: 90,
    fovDeg: 70,
    rangeM: 200,
    mediaType: "video",
    mediaUrl: yt("DjdUEyjx8GM"),
    sourceLabel: "ライブカメラDB",
    sourceUrl: "https://livecam.asia/",
  },
  {
    id: "sumida-river",
    name: "隅田川・浅草（河川）",
    type: "河川カメラ",
    country: "日本",
    region: "東京",
    lat: 35.7105,
    lon: 139.801,
    headingDeg: 160,
    fovDeg: 65,
    rangeM: 180,
    mediaType: "video",
    mediaUrl: yt("IFzpwTnv23w"),
    sourceLabel: "ライブカメラ検索マップ（河川）",
    sourceUrl: "https://camera-map.com/",
  },
  {
    id: "arakawa",
    name: "荒川・河川敷",
    type: "河川カメラ",
    country: "日本",
    region: "東京",
    lat: 35.74,
    lon: 139.82,
    headingDeg: 210,
    fovDeg: 60,
    rangeM: 220,
    mediaType: "image",
    mediaUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Arakawa_River_in_Tokyo.jpg/640px-Arakawa_River_in_Tokyo.jpg",
    sourceLabel: "ライブカメラDB（河川）",
    sourceUrl: "https://livecam.asia/",
  },
  {
    id: "tamagawa",
    name: "多摩川・二子玉川",
    type: "河川カメラ",
    country: "日本",
    region: "東京",
    lat: 35.611,
    lon: 139.63,
    headingDeg: 250,
    fovDeg: 70,
    rangeM: 200,
    mediaType: "image",
    mediaUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Tama_River_Futako-Tamagawa.jpg/640px-Tama_River_Futako-Tamagawa.jpg",
    sourceLabel: "ライブカメラ検索マップ",
    sourceUrl: "https://camera-map.com/",
  },
  {
    id: "yodogawa",
    name: "淀川・大阪（河川）",
    type: "河川カメラ",
    country: "日本",
    region: "大阪",
    lat: 34.72,
    lon: 135.48,
    headingDeg: 100,
    fovDeg: 60,
    rangeM: 250,
    mediaType: "image",
    mediaUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Yodo_River_Osaka.jpg/640px-Yodo_River_Osaka.jpg",
    sourceLabel: "ライブカメラDB",
    sourceUrl: "https://livecam.asia/",
  },
  {
    id: "osaka-dotonbori",
    name: "大阪・道頓堀",
    type: "ライブカメラ",
    country: "日本",
    region: "大阪",
    lat: 34.6687,
    lon: 135.5013,
    headingDeg: 90,
    fovDeg: 70,
    rangeM: 120,
    mediaType: "video",
    mediaUrl: yt("DjdUEyjx8GM"),
    sourceLabel: "YouTube 道頓堀ライブ",
    sourceUrl:
      "https://www.youtube.com/results?search_query=%E9%81%93%E9%A0%93%E5%A0%80+%E3%83%A9%E3%82%A4%E3%83%96%E3%82%AB%E3%83%A1%E3%83%A9",
  },
  {
    id: "kyoto-gion",
    name: "京都・祇園",
    type: "個人カメラ",
    country: "日本",
    region: "京都",
    lat: 35.0037,
    lon: 135.778,
    headingDeg: 180,
    fovDeg: 50,
    rangeM: 100,
    mediaType: "video",
    mediaUrl: yt("IFzpwTnv23w"),
    sourceLabel: "ライブカメラDB",
    sourceUrl: "https://livecam.asia/",
  },
  {
    id: "sapporo-odori",
    name: "札幌・大通",
    type: "固定カメラ",
    country: "日本",
    region: "北海道",
    lat: 43.06,
    lon: 141.35,
    headingDeg: 0,
    fovDeg: 65,
    rangeM: 160,
    mediaType: "video",
    mediaUrl: yt("1-iS7LArP0Y"),
    sourceLabel: "ライブカメラ検索マップ",
    sourceUrl: "https://camera-map.com/",
  },
  {
    id: "fukuoka-tenjin",
    name: "福岡・天神",
    type: "道路カメラ",
    country: "日本",
    region: "福岡",
    lat: 33.59,
    lon: 130.4,
    headingDeg: 45,
    fovDeg: 60,
    rangeM: 140,
    mediaType: "video",
    mediaUrl: yt("DjdUEyjx8GM"),
    sourceLabel: "ライブカメラDB",
    sourceUrl: "https://livecam.asia/",
  },
  {
    id: "nagoya-sakae",
    name: "名古屋・栄",
    type: "ライブカメラ",
    country: "日本",
    region: "愛知",
    lat: 35.1709,
    lon: 136.9075,
    headingDeg: 90,
    fovDeg: 65,
    rangeM: 130,
    mediaType: "video",
    mediaUrl: yt("IFzpwTnv23w"),
    sourceLabel: "YouTube ライブ",
    sourceUrl: "https://livecam.asia/",
  },
  {
    id: "fuji-view",
    name: "富士山展望",
    type: "個人カメラ",
    country: "日本",
    region: "山梨",
    lat: 35.3606,
    lon: 138.7274,
    headingDeg: 0,
    fovDeg: 80,
    rangeM: 400,
    mediaType: "video",
    mediaUrl: yt("1-iS7LArP0Y"),
    sourceLabel: "YouTube 富士山ライブ",
    sourceUrl:
      "https://www.youtube.com/results?search_query=%E5%AF%8C%E5%A3%AB%E5%B1%B1+%E3%83%A9%E3%82%A4%E3%83%96%E3%82%AB%E3%83%A1%E3%83%A9",
  },
  {
    id: "kamakura-coast",
    name: "鎌倉海岸",
    type: "個人カメラ",
    country: "日本",
    region: "神奈川",
    lat: 35.309,
    lon: 139.535,
    headingDeg: 180,
    fovDeg: 70,
    rangeM: 200,
    mediaType: "image",
    mediaUrl:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Yuigahama_Beach_Kamakura.jpg/640px-Yuigahama_Beach_Kamakura.jpg",
    sourceLabel: "ライブカメラDB",
    sourceUrl: "https://livecam.asia/",
  },
  {
    id: "nyc-times-square",
    name: "ニューヨーク・タイムズスクエア",
    type: "ライブカメラ",
    country: "アメリカ",
    region: "ニューヨーク",
    lat: 40.758,
    lon: -73.9855,
    headingDeg: 180,
    fovDeg: 75,
    rangeM: 150,
    mediaType: "video",
    mediaUrl: yt("AdUw5RdyZxI"),
    sourceLabel: "Webcamera24 / YouTube",
    sourceUrl: "https://webcamera24.com/ja/",
  },
  {
    id: "london-piccadilly",
    name: "ロンドン・ピカデリー",
    type: "ライブカメラ",
    country: "イギリス",
    region: "ロンドン",
    lat: 51.51,
    lon: -0.134,
    headingDeg: 90,
    fovDeg: 70,
    rangeM: 140,
    mediaType: "video",
    mediaUrl: yt("4qdC6tQ8j5Q"),
    sourceLabel: "Webcamera24",
    sourceUrl: "https://webcamera24.com/ja/",
  },
  {
    id: "paris-eiffel",
    name: "パリ・エッフェル塔周辺",
    type: "ライブカメラ",
    country: "フランス",
    region: "パリ",
    lat: 48.8584,
    lon: 2.2945,
    headingDeg: 45,
    fovDeg: 60,
    rangeM: 200,
    mediaType: "video",
    mediaUrl: yt("iJzyR9nxmPY"),
    sourceLabel: "Webcamera24",
    sourceUrl: "https://webcamera24.com/ja/",
  },
  {
    id: "singapore-marina",
    name: "シンガポール・マリーナベイ",
    type: "ライブカメラ",
    country: "シンガポール",
    region: "マリーナベイ",
    lat: 1.2834,
    lon: 103.8607,
    headingDeg: 270,
    fovDeg: 65,
    rangeM: 180,
    mediaType: "video",
    mediaUrl: yt("DjdUEyjx8GM"),
    sourceLabel: "Webcamera24",
    sourceUrl: "https://webcamera24.com/ja/",
  },
  {
    id: "seoul-myeongdong",
    name: "ソウル・明洞",
    type: "ライブカメラ",
    country: "韓国",
    region: "ソウル",
    lat: 37.5636,
    lon: 126.9869,
    headingDeg: 0,
    fovDeg: 70,
    rangeM: 120,
    mediaType: "video",
    mediaUrl: yt("IFzpwTnv23w"),
    sourceLabel: "Webcamera24",
    sourceUrl: "https://webcamera24.com/ja/",
  },
];

export const GROUND_CAMERA_DIRECTORIES = [
  { label: "ライブカメラDB", url: "https://livecam.asia/", note: "国内3.6万ヶ所超" },
  { label: "ライブカメラ検索マップ", url: "https://camera-map.com/", note: "地図・雨雲連動" },
  { label: "Webcamera24", url: "https://webcamera24.com/ja/", note: "海外都市・ビーチ" },
  {
    label: "YouTube ライブ検索",
    url: "https://www.youtube.com/results?search_query=%E3%83%A9%E3%82%A4%E3%83%96%E3%82%AB%E3%83%A1%E3%83%A9",
    note: "4K 街頭配信",
  },
] as const;

export const GROUND_PIN_COLORS = {
  video: "#fb923c",
  image: "#38bdf8",
} as const;
